In [32]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [15]:
with tf.compat.v1.Session() as sess:
    frase = tf.constant('Olá, Mundo!')
    rodar = sess.run(frase)
print(rodar.decode('UTF-8'))

Olá, Mundo!


In [17]:
frase = tf.constant('Olá, mundo!')
tf.print(frase)

Olá, mundo!


In [23]:
a = tf.constant(5)
b = tf.constant(3)
c = tf.constant(2)

d = tf.multiply(a, b)
e = tf.add(b, c)
f = tf.subtract(d, e)

tf.print(d, e, f)

15 5 10


In [30]:
type(f)

tensorflow.python.framework.ops.EagerTensor

In [40]:
a = tf.constant(2)  # 1x1
b = tf.constant([3, 1, 5, 8, 6])  # 1xn
c = tf.constant([[2, 0, 4],[3, 5, 7]])  #nxn

tf.print(c)

[[2 0 4]
 [3 5 7]]


In [48]:
a1 = np.array(2)
b1 = np.array([3, 1, 5, 8, 6])
c1 = np.array([[2, 0, 4],[3, 5, 7]])

In [47]:
print(a.shape)
print(a1.shape)
print(b.shape)
print(b1.shape)
print(c.shape)
print(c1.shape)

()
()
(5,)
(5,)
(2, 3)
(2, 3)


In [55]:
const = tf.constant(4)
const_1 = tf.constant(4, dtype = tf.float64)  # inserindo o tipo

In [56]:
print(const)
print(const_1)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4.0, shape=(), dtype=float64)


## Multiplicação de matrizes

In [76]:
A = tf.constant([[1, 2, 3], [4, 5, 6]])
B = tf.constant([[0, 0], [1, 0], [0, 1]])
x = tf.constant([0, 1, 0])

In [60]:
tf.print(A)
tf.print(B)

[[1 2 3]
 [4 5 6]]
[[0 0]
 [1 0]
 [0 1]]


In [61]:
# multiplicando as matrizes
resultado = tf.matmul(A, B)
tf.print(resultado)

[[2 3]
 [5 6]]


In [64]:
# dá erro, não é possível multiplicar essas matrizes
# resultado = tf.matmul(A, x)

In [78]:
# expandindo x para ter a quantidade de linhas igual a quantidade de colunas de A
x = tf.expand_dims(x, 1) # na prática, transpos a matriz

In [73]:
resultado_2 = tf.matmul(A, x)
resultado_2

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]])>

In [81]:
transposta = tf.transpose(A)

In [82]:
tf.print(A)
tf.print(transposta)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## Variáveis

In [83]:
variavel = tf.Variable(2)

In [84]:
tf.print(variavel)

2


In [86]:
# criando uma matriz aleatória shape (3, 5)
matriz = tf.random.normal((3, 5), 0, 1) # ((linhas, colunas), média, desvio padrão)

In [88]:
tf.print(matriz)

[[0.495778412 0.0439552478 -1.04650044 -0.355926812 -0.7610569]
 [-1.61652589 -1.03163838 -0.406583697 0.634820819 0.827424109]
 [1.64856875 0.390189528 1.81746519 -1.00171459 0.58594805]]


In [89]:
variavel_2 = tf.Variable(matriz)

In [90]:
# imprimindo a variável matriz
tf.print(variavel_2)

[[0.495778412 0.0439552478 -1.04650044 -0.355926812 -0.7610569]
 [-1.61652589 -1.03163838 -0.406583697 0.634820819 0.827424109]
 [1.64856875 0.390189528 1.81746519 -1.00171459 0.58594805]]


In [92]:
# tipos das variáveis
print(matriz)     # tensor
print(variavel_2) # variable

tf.Tensor(
[[ 0.4957784   0.04395525 -1.0465004  -0.3559268  -0.7610569 ]
 [-1.6165259  -1.0316384  -0.4065837   0.6348208   0.8274241 ]
 [ 1.6485687   0.39018953  1.8174652  -1.0017146   0.58594805]], shape=(3, 5), dtype=float32)
<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[ 0.4957784 ,  0.04395525, -1.0465004 , -0.3559268 , -0.7610569 ],
       [-1.6165259 , -1.0316384 , -0.4065837 ,  0.6348208 ,  0.8274241 ],
       [ 1.6485687 ,  0.39018953,  1.8174652 , -1.0017146 ,  0.58594805]],
      dtype=float32)>


## Placeholders

In [94]:
dados_x = np.random.randn(4, 8)   # cria matriz de 4 linhas e 8 colunas com números aleatórios
dados_w = np.random.randn(8, 2)   # cria matriz de 8 linhas e 2 colunas com números aleatórios

b = tf.random.normal((4, 2), 0, 1, tf.float64)   # cria matriz (tensor) de 4 linhas e 2 colunas

operacao = tf.matmul(dados_x, dados_w) + b   # [4, 8] x [8, 2] = [4, 2]
maximo = tf.math.reduce_max(operacao) # encontra o maior valor da matriz operacao

In [95]:
tf.print(operacao)  # matriz [4, 2]
tf.print(maximo)    # valor máximo

[[-0.46350922758330343 3.7562033949233449]
 [-3.7981461128592371 0.17751443813944789]
 [1.2235521780729126 2.4907941059808154]
 [0.051428160361012831 4.040647054647172]]
4.040647054647172


In [96]:
x1 = np.random.randn(4,8)  
w1 = np.random.randn(8,2)


x2 = np.random.randn(4,8)  
w2 = np.random.randn(8,2)


x3 = np.random.randn(4,8)  
w3 = np.random.randn(8,2)

x4 = np.random.randn(4,8)  
w4 = np.random.randn(8,2)

x5 = np.random.randn(4,8)  
w5 = np.random.randn(8,2)

lista_x = [x1, x2, x3, x4, x5]
lista_w = [w1, w2, w3, w4, w5]
lista_saida = []

b = tf.random.normal((4,2),0,1, tf.float64)   # cria matriz (tensor) de 4 linhas e 2 colunas com números aleatórios

for i in range(5):
    operacao = (tf.matmul(lista_x[i], lista_w[i])) + b
    maximo = tf.reduce_max(operacao) # encontra o maior valor da matriz operacao
    lista_saida.append(maximo)

In [ ]:
tf.print(lista_saida)